### ISSUE TITLE
improper parsing of rpName and bpName properties in the config.json

### ISSUE THREAD

**Issue by iEnis** [Bedrock-OSS/regolith#307]
when trying to rename the exported behavior and resource pack using the bpName and rpName properties in the config.json by just doing `"bpName": "MyName"` it throws an error, this gets fixed by just parsing in another set of parenthesies into my bpName like this `"bpName": "\"MyName\""`

**Comment by Nusiq** [comment]
This behavior is intentional. You should use single quotes to set the names. That's because the names are set using go-simple-eval. This AFAIK is currently not properly documented but you can read about it in the new documentation, that I currently write: https://github.com/Bedrock-OSS/regolith-docs/blob/rewrite/docs/project-configuration/go-simple-eval.md
